from django.contrib import admin
from .models import Restaurant
"""
WHY use .models (relative import)?
The dot '.' means 'from THIS app's models.py'.
This is cleaner than writing 'from restaurant.models import Restaurant'.
Always use relative imports INSIDE an app — it makes
the app self-contained and easier to move or rename later.
BEGINNER MISTAKE: writing absolute imports inside the same app,
which breaks if you ever rename the app.
"""

@admin.register(Restaurant)
class RestaurantAdmin(admin.ModelAdmin):

    list_display = ['name', 'phone', 'is_active', 'created_at']
    """
    WHY these specific fields in list_display?
    name     → you need to identify the restaurant
    phone    → quick contact reference
    is_active → most important status to monitor
    created_at → see newest restaurants first
    These 4 give you everything you need at a glance
    without opening each record individually.
    """

    list_filter = ['is_active', 'created_at']
    """
    WHY list_filter on is_active?
    In admin you'll often need to see:
    - "show me only ACTIVE restaurants"
    - "show me only INACTIVE restaurants"
    list_filter adds a sidebar for this instantly.
    """

    search_fields = ['name', 'address', 'phone']
    """
    WHY search these 3 fields?
    Admin might search by:
    - restaurant name (most common)
    - address (to find by area/city)
    - phone (if customer calls with a complaint)
    Always think about HOW your admin will actually
    use the search before choosing search_fields.
    """

    ordering = ['-created_at']
    """
    WHY minus sign in ordering?
    '-created_at' = newest first (descending)
    'created_at'  = oldest first (ascending)
    For restaurants you always want newest at top.
    """

    readonly_fields = ['created_at']
    """
    WHY readonly?
    created_at is auto-generated by Django.
    Making it readonly means admin can SEE it
    but cannot accidentally edit or clear it.
    Always make auto-generated fields readonly.
    """

    list_editable = ['is_active']
    """
    WHY list_editable?
    is_active is the most frequently toggled field.
    list_editable lets you turn restaurants on/off
    directly from the list page with a checkbox —
    no need to open each restaurant one by one.
    RULE: fields in list_editable MUST also be
    in list_display — otherwise Django throws an error.
    """

    fieldsets = (
        ('Restaurant Info', {
            'fields': ('name', 'address', 'phone', 'logo')
        }),
        ('Status', {
            'fields': ('is_active',)
        }),
        ('Timestamps', {
            'fields': ('created_at',)
        }),
    )
    """
    WHY fieldsets?
    Without fieldsets all fields appear in one long
    unsorted block — confusing and unprofessional.
    fieldsets groups related fields into named sections.
    This is what your evaluator will see when they
    open a restaurant record in your admin panel.
    Always organize fieldsets logically:
    1. Main info first
    2. Status/settings second
    3. Timestamps last (least important)
    """